PWX-26709: fix the intermittent failure in the unit test (#2110)
Need to sleep a bit longer to ensure that that tasks get chance to run.

This was the failure in travis build:

--- FAIL: TestMulti (3.00s)
	Error Trace:	sched_test.go:106
	Error:		Should be true
	Messages:	count was 0 for task 0

FAIL

Signed-off-by: Neelesh Thakur <neelesh.thakur@purestorage.com>